name: Node.js CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      # TODO: Check following command: - run: npm test
    
      - name: Print Feedback
        run: echo "Hello, build was successful!"

